package net.staticstudios.prisons.lootboxes;

public enum LootBoxType {
    TOKEN("ewogICJ0aW1lc3RhbXAiIDogMTYwNTkwNzExNzgxMiwKICAicHJvZmlsZUlkIiA6ICJiYzRlZGZiNWYzNmM0OGE3YWM5ZjFhMzlkYzIzZjRmOCIsCiAgInByb2ZpbGVOYW1lIiA6ICI4YWNhNjgwYjIyNDYxMzQwIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QzNTAxZDhhYzg2MWY5NzgxNGQxMGNkNjRkYzQzNWMyMjljNGVjZWYxNTAxYWM3MzRkNDk5NjAwMDdlN2Y2MWMiCiAgICB9CiAgfQp9");

    String base64Texture;

    LootBoxType(String skullBase64texture) {
        this.base64Texture = skullBase64texture;
    }
}
