package me.staticstudios.prisons.gameplay.customItems;

import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;

import java.util.ArrayList;
import java.util.List;

public class Kits {

    public static List<Kit> kits = new ArrayList<>();



    public static Kit TIER1 = new Kit() {};
    public static Kit TIER2 = new Kit();
    public static Kit TIER3 = new Kit();
    public static Kit TIER4 = new Kit();
    public static Kit TIER5 = new Kit();
    public static Kit TIER6 = new Kit();
    public static Kit POTION = new Kit();
    public static Kit WEAPON = new Kit();

    public static void initialize() {
        //Tier 1
        TIER1.name = ChatColor.AQUA + "Kit Tier 1";
        TIER1.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Helmet: Protection 1 | Unbreaking 1");
        TIER1.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Chestplate: Protection 1 | Unbreaking 1");
        TIER1.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Leggings: Protection 1 | Unbreaking 1");
        TIER1.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Boots: Protection 1 | Unbreaking 1");
        TIER1.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Sword: Sharpness 1 | Unbreaking 1");
        TIER1.whatComesWithTheKit.add(ChatColor.GREEN + " -Bread: 64");
        TIER1.helmet = new ItemStack(Material.IRON_HELMET);
        TIER1.helmet.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        TIER1.helmet.addEnchantment(Enchantment.DURABILITY, 1);
        TIER1.chestplate = new ItemStack(Material.IRON_CHESTPLATE);
        TIER1.chestplate.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        TIER1.chestplate.addEnchantment(Enchantment.DURABILITY, 1);
        TIER1.leggings = new ItemStack(Material.IRON_LEGGINGS);
        TIER1.leggings.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        TIER1.leggings.addEnchantment(Enchantment.DURABILITY, 1);
        TIER1.boots = new ItemStack(Material.IRON_BOOTS);
        TIER1.boots.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        TIER1.boots.addEnchantment(Enchantment.DURABILITY, 1);
        TIER1.sword = new ItemStack(Material.IRON_SWORD);
        TIER1.sword.addEnchantment(Enchantment.DAMAGE_ALL, 1);
        TIER1.sword.addEnchantment(Enchantment.DURABILITY, 1);
        TIER1.food1 = new ItemStack(Material.BREAD);
        TIER1.food1.setAmount(64);
        kits.add(TIER1);
        //Tier 2
        TIER2.name = ChatColor.AQUA + "Kit Tier 2";
        TIER2.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Helmet: Protection 2 | Unbreaking 2");
        TIER2.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Chestplate: Protection 2 | Unbreaking 2");
        TIER2.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Leggings: Protection 2 | Unbreaking 2");
        TIER2.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Boots: Protection 2 | Unbreaking 2");
        TIER2.whatComesWithTheKit.add(ChatColor.GREEN + " -Iron Sword: Sharpness 2 | Unbreaking 2");
        TIER2.whatComesWithTheKit.add(ChatColor.GREEN + " -Bread: 64");
        TIER2.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Apple: 1");
        TIER2.helmet = new ItemStack(Material.IRON_HELMET);
        TIER2.helmet.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        TIER2.helmet.addEnchantment(Enchantment.DURABILITY, 2);
        TIER2.chestplate = new ItemStack(Material.IRON_CHESTPLATE);
        TIER2.chestplate.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        TIER2.chestplate.addEnchantment(Enchantment.DURABILITY, 2);
        TIER2.leggings = new ItemStack(Material.IRON_LEGGINGS);
        TIER2.leggings.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        TIER2.leggings.addEnchantment(Enchantment.DURABILITY, 2);
        TIER2.boots = new ItemStack(Material.IRON_BOOTS);
        TIER2.boots.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        TIER2.boots.addEnchantment(Enchantment.DURABILITY, 2);
        TIER2.sword = new ItemStack(Material.IRON_SWORD);
        TIER2.sword.addEnchantment(Enchantment.DAMAGE_ALL, 2);
        TIER2.sword.addEnchantment(Enchantment.DURABILITY, 2);
        TIER2.food1 = new ItemStack(Material.BREAD);
        TIER2.food1.setAmount(64);
        TIER2.food2 = new ItemStack(Material.GOLDEN_APPLE);
        TIER2.food2.setAmount(1);
        kits.add(TIER2);
        //tier 3
        TIER3.name = ChatColor.AQUA + "Kit Tier 3";
        TIER3.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Helmet: Protection 1 | Unbreaking 1");
        TIER3.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Chestplate: Protection 1 | Unbreaking 1");
        TIER3.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Leggings: Protection 1 | Unbreaking 1");
        TIER3.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Boots: Protection 1 | Unbreaking 1");
        TIER3.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Sword: Sharpness 1 | Unbreaking 1");
        TIER3.whatComesWithTheKit.add(ChatColor.GREEN + " -Bread: 64");
        TIER3.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Apple: 2");
        TIER3.helmet = new ItemStack(Material.DIAMOND_HELMET);
        TIER3.helmet.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        TIER3.helmet.addEnchantment(Enchantment.DURABILITY, 1);
        TIER3.chestplate = new ItemStack(Material.DIAMOND_CHESTPLATE);
        TIER3.chestplate.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        TIER3.chestplate.addEnchantment(Enchantment.DURABILITY, 1);
        TIER3.leggings = new ItemStack(Material.DIAMOND_LEGGINGS);
        TIER3.leggings.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        TIER3.leggings.addEnchantment(Enchantment.DURABILITY, 1);
        TIER3.boots = new ItemStack(Material.DIAMOND_BOOTS);
        TIER3.boots.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        TIER3.boots.addEnchantment(Enchantment.DURABILITY, 1);
        TIER3.sword = new ItemStack(Material.DIAMOND_SWORD);
        TIER3.sword.addEnchantment(Enchantment.DAMAGE_ALL, 1);
        TIER3.sword.addEnchantment(Enchantment.DURABILITY, 1);
        TIER3.food1 = new ItemStack(Material.BREAD);
        TIER3.food1.setAmount(64);
        TIER3.food2 = new ItemStack(Material.GOLDEN_APPLE);
        TIER3.food2.setAmount(2);
        kits.add(TIER3);
        //tier 4
        TIER4.name = ChatColor.AQUA + "Kit Tier 4";
        TIER4.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Helmet: Protection 2 | Unbreaking 2");
        TIER4.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Chestplate: Protection 2 | Unbreaking 2");
        TIER4.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Leggings: Protection 2 | Unbreaking 2");
        TIER4.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Boots: Protection 2 | Unbreaking 2");
        TIER4.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Sword: Sharpness 2 | Unbreaking 2");
        TIER4.whatComesWithTheKit.add(ChatColor.GREEN + " -Bread: 64");
        TIER4.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Apple: 5");
        TIER4.helmet = new ItemStack(Material.DIAMOND_HELMET);
        TIER4.helmet.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        TIER4.helmet.addEnchantment(Enchantment.DURABILITY, 2);
        TIER4.chestplate = new ItemStack(Material.DIAMOND_CHESTPLATE);
        TIER4.chestplate.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        TIER4.chestplate.addEnchantment(Enchantment.DURABILITY, 2);
        TIER4.leggings = new ItemStack(Material.DIAMOND_LEGGINGS);
        TIER4.leggings.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        TIER4.leggings.addEnchantment(Enchantment.DURABILITY, 2);
        TIER4.boots = new ItemStack(Material.DIAMOND_BOOTS);
        TIER4.boots.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        TIER4.boots.addEnchantment(Enchantment.DURABILITY, 2);
        TIER4.sword = new ItemStack(Material.DIAMOND_SWORD);
        TIER4.sword.addEnchantment(Enchantment.DAMAGE_ALL, 2);
        TIER4.sword.addEnchantment(Enchantment.DURABILITY, 2);
        TIER4.food1 = new ItemStack(Material.BREAD);
        TIER4.food1.setAmount(64);
        TIER4.food2 = new ItemStack(Material.GOLDEN_APPLE);
        TIER4.food2.setAmount(5);
        kits.add(TIER4);
        //tier 5
        TIER5.name = ChatColor.AQUA + "Kit Tier 5";
        TIER5.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Helmet: Protection 3 | Unbreaking 3");
        TIER5.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Chestplate: Protection 3 | Unbreaking 3");
        TIER5.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Leggings: Protection 3 | Unbreaking 3");
        TIER5.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Boots: Protection 3 | Unbreaking 3");
        TIER5.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Sword: Sharpness 3 | Unbreaking 3");
        TIER5.whatComesWithTheKit.add(ChatColor.GREEN + " -Bread: 64");
        TIER5.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Apple: 8");
        TIER5.helmet = new ItemStack(Material.DIAMOND_HELMET);
        TIER5.helmet.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3);
        TIER5.helmet.addEnchantment(Enchantment.DURABILITY, 3);
        TIER5.chestplate = new ItemStack(Material.DIAMOND_CHESTPLATE);
        TIER5.chestplate.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3);
        TIER5.chestplate.addEnchantment(Enchantment.DURABILITY, 3);
        TIER5.leggings = new ItemStack(Material.DIAMOND_LEGGINGS);
        TIER5.leggings.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3);
        TIER5.leggings.addEnchantment(Enchantment.DURABILITY, 3);
        TIER5.boots = new ItemStack(Material.DIAMOND_BOOTS);
        TIER5.boots.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 3);
        TIER5.boots.addEnchantment(Enchantment.DURABILITY, 3);
        TIER5.sword = new ItemStack(Material.DIAMOND_SWORD);
        TIER5.sword.addEnchantment(Enchantment.DAMAGE_ALL, 3);
        TIER5.sword.addEnchantment(Enchantment.DURABILITY, 3);
        TIER5.food1 = new ItemStack(Material.BREAD);
        TIER5.food1.setAmount(64);
        TIER5.food2 = new ItemStack(Material.GOLDEN_APPLE);
        TIER5.food2.setAmount(8);
        kits.add(TIER5);
        //tier 6
        TIER6.name = ChatColor.AQUA + "Kit Tier 6";
        TIER6.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Helmet: Protection 4 | Unbreaking 4");
        TIER6.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Chestplate: Protection 4 | Unbreaking 4");
        TIER6.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Leggings: Protection 4 | Unbreaking 4");
        TIER6.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Boots: Protection 4 | Unbreaking 4");
        TIER6.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Sword: Sharpness 4 | Unbreaking 4");
        TIER6.whatComesWithTheKit.add(ChatColor.GREEN + " -Bread: 64");
        TIER6.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Apple: 12");
        TIER6.helmet = new ItemStack(Material.DIAMOND_HELMET);
        TIER6.helmet.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4);
        TIER6.helmet.addEnchantment(Enchantment.DURABILITY, 3);
        TIER6.chestplate = new ItemStack(Material.DIAMOND_CHESTPLATE);
        TIER6.chestplate.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4);
        TIER6.chestplate.addEnchantment(Enchantment.DURABILITY, 3);
        TIER6.leggings = new ItemStack(Material.DIAMOND_LEGGINGS);
        TIER6.leggings.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4);
        TIER6.leggings.addEnchantment(Enchantment.DURABILITY, 3);
        TIER6.boots = new ItemStack(Material.DIAMOND_BOOTS);
        TIER6.boots.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 4);
        TIER6.boots.addEnchantment(Enchantment.DURABILITY, 3);
        TIER6.sword = new ItemStack(Material.DIAMOND_SWORD);
        TIER6.sword.addEnchantment(Enchantment.DAMAGE_ALL, 4);
        TIER6.sword.addEnchantment(Enchantment.DURABILITY, 3);
        TIER6.food1 = new ItemStack(Material.BREAD);
        TIER6.food1.setAmount(64);
        TIER6.food2 = new ItemStack(Material.GOLDEN_APPLE);
        TIER6.food2.setAmount(12);
        kits.add(TIER6);
        //potion kit
        POTION.name = ChatColor.AQUA + "Kit Potion";
        POTION.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Helmet: Protection 1 | Unbreaking 1");
        POTION.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Chestplate: Protection 1 | Unbreaking 1");
        POTION.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Leggings: Protection 1 | Unbreaking 1");
        POTION.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Boots: Protection 1 | Unbreaking 1");
        POTION.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Sword: Sharpness 1 | Unbreaking 1");
        POTION.whatComesWithTheKit.add(ChatColor.GREEN + " -Bread: 64");
        POTION.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Apple: 6");
        POTION.helmet = new ItemStack(Material.GOLDEN_HELMET);
        POTION.helmet.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        POTION.helmet.addEnchantment(Enchantment.DURABILITY, 1);
        POTION.chestplate = new ItemStack(Material.GOLDEN_CHESTPLATE);
        POTION.chestplate.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        POTION.chestplate.addEnchantment(Enchantment.DURABILITY, 1);
        POTION.leggings = new ItemStack(Material.GOLDEN_LEGGINGS);
        POTION.leggings.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        POTION.leggings.addEnchantment(Enchantment.DURABILITY, 1);
        POTION.boots = new ItemStack(Material.GOLDEN_BOOTS);
        POTION.boots.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        POTION.boots.addEnchantment(Enchantment.DURABILITY, 1);
        POTION.food2 = new ItemStack(Material.GOLDEN_APPLE);
        POTION.food2.setAmount(6);
        //healing potion
        POTION.potion1 = new ItemStack(Material.SPLASH_POTION);
        PotionMeta healingmeta = (PotionMeta) POTION.potion1.getItemMeta();
        healingmeta.addCustomEffect(new PotionEffect(PotionEffectType.HEAL, 50, 0), true);
        POTION.potion1.setItemMeta(healingmeta);
        ItemMeta meta = POTION.potion1.getItemMeta();
        meta.setDisplayName("Splash Healing Potion");
        POTION.potion1.setItemMeta(meta);
        POTION.potion2 = new ItemStack(POTION.potion1);
        POTION.potion3 = new ItemStack(POTION.potion1);
        POTION.potion4 = new ItemStack(POTION.potion1);
        POTION.potion5 = new ItemStack(POTION.potion1);
        //Regen Potion
        POTION.potion6 = new ItemStack(Material.POTION);
        PotionMeta regenMeta = (PotionMeta) POTION.potion6.getItemMeta();
        regenMeta.addCustomEffect(new PotionEffect(PotionEffectType.REGENERATION, 440, 1), true);
        POTION.potion6.setItemMeta(regenMeta);
        ItemMeta meta1 = POTION.potion6.getItemMeta();
        meta.setDisplayName("Regeneration Potion");
        POTION.potion6.setItemMeta(meta1);
        POTION.potion7 = new ItemStack(POTION.potion6);
        POTION.potion8 = new ItemStack(POTION.potion6);
        //Speed Potion
        POTION.potion9 = new ItemStack(Material.POTION);
        PotionMeta speedMeta = (PotionMeta) POTION.potion9.getItemMeta();
        speedMeta.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 9600, 1), true);
        POTION.potion9.setItemMeta(speedMeta);
        ItemMeta meta2 = POTION.potion9.getItemMeta();
        meta.setDisplayName("Speed Potion");
        POTION.potion9.setItemMeta(meta2);
        POTION.potion10 = new ItemStack(POTION.potion9);
        POTION.potion11 = new ItemStack(POTION.potion9);
        POTION.potion12 = new ItemStack(Material.POTION);
        PotionMeta strengthMeta = (PotionMeta) POTION.potion12.getItemMeta();
        strengthMeta.addCustomEffect(new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 9600, 1), true);
        POTION.potion12.setItemMeta(strengthMeta);
        ItemMeta meta3 = POTION.potion12.getItemMeta();
        meta.setDisplayName("Strength Potion");
        POTION.potion12.setItemMeta(meta3);
        POTION.potion13 = new ItemStack(POTION.potion12);
        kits.add(POTION);
        //weapons kit
        WEAPON.name = ChatColor.AQUA + "Kit Weapons";
        WEAPON.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Sword: Sharpness 4 | Unbreaking 3");
        WEAPON.whatComesWithTheKit.add(ChatColor.GREEN + " -Diamond Axe: Protection 4 | Unbreaking 3");
        WEAPON.whatComesWithTheKit.add(ChatColor.GREEN + " -Bow: Power 4 | Punch 1");
        WEAPON.whatComesWithTheKit.add(ChatColor.GREEN + " -Arrow: 64");
        WEAPON.whatComesWithTheKit.add(ChatColor.GREEN + " -Bread: 64");
        WEAPON.whatComesWithTheKit.add(ChatColor.GREEN + " -Golden Apple: 2");
        WEAPON.sword = new ItemStack(Material.DIAMOND_SWORD);
        WEAPON.sword.addEnchantment(Enchantment.DAMAGE_ALL, 4);
        WEAPON.sword.addEnchantment(Enchantment.DURABILITY, 3);
        WEAPON.sword = new ItemStack(Material.DIAMOND_AXE);
        WEAPON.axe = new ItemStack(Material.DIAMOND_AXE);
        WEAPON.axe.addEnchantment(Enchantment.DAMAGE_ALL, 4);
        WEAPON.axe.addEnchantment(Enchantment.DURABILITY, 3);
        WEAPON.bow = new ItemStack(Material.BOW);
        WEAPON.bow.addEnchantment(Enchantment.ARROW_DAMAGE, 4);
        WEAPON.bow.addEnchantment(Enchantment.DURABILITY, 3);
        WEAPON.bow.addEnchantment(Enchantment.ARROW_KNOCKBACK, 1);
        WEAPON.arrow = new ItemStack(Material.ARROW);
        WEAPON.arrow.setAmount(64);
        WEAPON.food1 = new ItemStack(Material.BREAD);
        WEAPON.food1.setAmount(64);
        WEAPON.food2 = new ItemStack(Material.GOLDEN_APPLE);
        WEAPON.food2.setAmount(2);
        kits.add(WEAPON);
    }
}
