package me.staticstudios.prisons.utils;

import java.math.BigInteger;

public class StaticVars {
    public static final int VOTES_NEEDED_FOR_VOTE_PARTY = 50;
    public static final Long[] amountOfPrestigesRequiredForPrestigeMines = {
            5L,
            50L,
            100L,
            250L,
            500L,
            1000L,
            2500L,
            5000L,
            7500L,
            10000L,
            15000L,
            25000L,
            50000L,
            100000L,
            250000L,
    };
    public static final String[] publicMineWorldNames = {
            "publicmine-a",
            "publicmine-b",
            "publicmine-c",
            "publicmine-d",
            "publicmine-e",
            "publicmine-f",
            "publicmine-g",
            "publicmine-h",
            "publicmine-i",
            "publicmine-j",
            "publicmine-k",
            "publicmine-l",
            "publicmine-m",
            "publicmine-n",
            "publicmine-o",
            "publicmine-p",
            "publicmine-q",
            "publicmine-r",
            "publicmine-s",
            "publicmine-t",
            "publicmine-u",
            "publicmine-v",
            "publicmine-w",
            "publicmine-x",
            "publicmine-y",
            "publicmine-z"
    };
    public static final char[] A_THROUGH_Z = {
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
    };

}
